### ISSUE TITLE
Unable to navigate away from shell selection

### ISSUE THREAD

**Issue by volfco** [cylgom/ly#11]
When I configure ly on an Ubuntu 16.04 system, I am unable to return the cursor to the username field when I switch the shell from "console" to anything. Filling out both username and password then switching to the shell field, I'm unable to submit the form (enter).

**Comment by cylgom** [comment]
This is the expected behaviour of the desktop field: it is not a text input, but a list. You can change the target with the left/right arrows when it's focused, or type the exact name of the desired entry. If what you typed is not an element of the list though, you won't be able to escape the field with enter. The "shell" entry automatically starts your user's configured shell, it does not expect you to replace the entry's name by that of the shell you want. Can you confirm I did not misunderstood your issue ? Thanks :)
