### ISSUE TITLE
Suggestion for xsetup.sh

### ISSUE THREAD

**Issue by skidnik** [cylgom/ly#111]
Where:
OS: ArchLinux
WM: i3

Why:
Currently Ly is loading the X session without login shell (/etc/profle and similar), XDG_ and many other X11 related variables set.

Ly's `xsetup.sh` currently contains this:

```
#!/bin/sh

~/.xsession
exec $@
```

As far as I can tell this is trying to rely on `~/.xsession` file to load whatever environment is set for X and login shells. In it's current state it doesn't work (have to `. ~/.xsession` and better check if file exists before). That file is only supposed to contain startup entries and is not executed this way at all.

I suggest using e.g. a [LightDM Xsession wrapper](https://github.com/CanonicalLtd/lightdm/blob/master/debian/lightdm-session) to properly load the X environment.

**Comment by gjorando** [comment]
I agree. As a result, environment variables aren't properly set (eg. LANG is not set).

**Comment by pandaxtc** [comment]
Third-ed(?), I just went through a lot of pain trying to figure out why my LANG variable wasn't being set when I realized it was because of this.

**Comment by cylgom** [comment]
Thank you! I didn't know that, you just solved most of the weird issues out there.
LightDM's implementation didn't work for me though so I settled for [SDDM's version](https://github.com/sddm/sddm/blob/develop/data/scripts/Xsession).

**Comment by JBlocklove** [comment]
Can you elaborate on what you mean that LightDM's implementation didn't work for you? I just ask because I'm switching from LightDM and I'm trying to find everything that functions differently. For example, since I use zsh I need to have ~/.zprofile, rather than the normal ~/.profile. I'm intrigued to see if we could make it so that one of multiple Xsession wrappers could be used based on the config file.
