### ISSUE TITLE
Support XDG dir specification.

### ISSUE THREAD

**Issue by K41eb** [cylgom/ly#157]
This is an enhancement suggestion.

To avoid a bloated `$HOME` directory I started implementing the [XDG Base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) which is a simple convention that:
> defines where files should be looked for by defining one or more base directories relative to which files should be located

In other words, instead of having a bajillion `.dotfile`s in `$HOME`, you put them in a `.directory` of your choosing, often defaulting to `$HOME/.config/appname`. There are several other directories for other kind of files, just read the specificaton.

So the idea would be to **try to store ly files in XDG Directories first** and then default to `$HOME`. This was motivated by the `.lyxauth` file I constantly see in my `$HOME`.

**Comment by PhilipConte** [comment]
This would be great. I wonder whether or not this should be added to the configurator instead though.

**Comment by buckshee** [comment]
XDG _**is**_ the bloat and isnt' stricly relevant to xauth, everything that's setting up or using XDG is being loaded after Ly, and with config in /etc it's meaninless for it.

Also " $HOME/.Xauthority default authority file if XAUTHORITY isn't defined." - `.lyxauth ` is hard coded probably related to the early stages Ly is at so you don't kill your session.

**Comment by cylgom** [comment]
I've been delaying this one for yeeeeears but it's fixed now (7296da456fac7755c7454b480f662fdf992c73d7).

@buckshee ~~I disagree and display managers are mostly bloat handlers anyway~~ yolo

**Comment by Kritiqual** [comment]
Sorry for bumping, but how do I move the .lyxauth file?

**Comment by Cavernosa** [comment]
@Kritiqual From a quick look at `src/login.c`, you need the env var `XDG_CONFIG_HOME` set up somehow, otherwise it will just fallback to your PWD (btw, shouldn't it fallback to `$HOME/.config` instead?)

**Comment by rbilk** [comment]
Don't quote me, I think most people usually export paths in bashrc or .profile files etc. I couldn't get .lyxauth to move to .config folder this way... I guess because the variable is exported after you have used ly to log in.

I managed to move .lyxauth to the .config folder by adding 
`XDG_CONFIG_HOME   DEFAULT=@{HOME}/.config`
to /etc/security/pam_env.conf
[https://wiki.archlinux.org/title/Environment_variables#Using_pam_env](url)
Is this an ok method?
 
I also tried to use etc/environment with standard `XDG_CONFIG_HOME="$HOME/.config"` but this just created a folder in my home directory called $HOME, not sure if an @ instead of $ would have solved issue.

**Comment by Cavernosa** [comment]
Hm, no idea how that worked for you since it actually searches for `XDG_CONFIG_DIR` instead of `XDG_CONFIG_HOME` (just found it)
Alternatively, it's also possible to create a script in `/etc/profile.d/`

From what I've seen, it seems that ly is incorrectly looking for `XDG_CONFIG_DIR`, and also not using `$HOME/.config` as a fallback, as specified in the xdg base dirs specification.

**Comment by rbilk** [comment]
Not sure, I wanted to move .lyaxauth and this was the first thing in search: https://github.com/fairyglade/ly/issues/233#issuecomment-1110164132

then found this: https://github.com/fairyglade/ly/commit/7296da456fac7755c7454b480f662fdf992c73d7 obviously it's old, hence the notice. Just checked src/login.c for a sanity check and it does say XDG_CONFIG_DIR instead of XDG_CONFIG_HOME.

Not sure how it worked then, I'm using the AUR package so maybe it's not quite as up to date?

Sorry, if I'm not much use. I'm not the most technical regarding source code etc - I just like tinkering with my system. So, thought I'd leave a reply

**Comment by Cavernosa** [comment]
yeah the AUR package is very old, there was a recent commit (#330) that changed this part of the code and thus brought the wrong name (XDG_CONFIG_DIR). I'm trying to make a fix (which brought me to another problem lol)
