### ISSUE TITLE
Gentoo / OpenRC Support

### ISSUE THREAD

**Issue by NamedKitten** [cylgom/ly#63]
Having support for OpenRC would be nice.
I will make a PR later with OpenRC compatibility and maybe even a ebuild for it in my overlay.

**Comment by cylgom** [comment]
Awesome, thank you for this! I've seen some people mistakenly thinking Ly requires systemd. This is not the case, I didn't test it outside systemd because I use Archlinux, but it should work fine. Well, actually there is that PAM_SYSTEMD constant I don't really understand (defined in login.c) but otherwise the installation instructions cover systemd just because that's what I'm using because of Arch (yes, I hate systemd, too).

**Comment by NamedKitten** [comment]
I use Arch and am migrating over to Gentoo as we speak. You got any way for me to contact you about this more? (like discord/telegram/whatever)

**Comment by cylgom** [comment]
I am cylgom#3702 on discord, feel free to ask me anything.

**Comment by hallabro** [comment]
Did you manage to create an OpenRC init script?

I struggled with it for a while [in my overlay](https://github.com/hallabro/hallabro-overlay/commit/cd0059d1f6340fe1ec7b6f78af825f4c68167f5f#diff-bef678d52866b187784d752678808de0) but I don't think it turned out very well. For now I just pass `/usr/bin/ly` to `agetty` in `inittab` but I'm not sure how I feel about that.

**Comment by cylgom** [comment]
OP stopped working on this. As for your inittab, changing the default `login` used by getty is fine, actually this is what you should do to change the tty login program. I don't recommend it though because if anything goes wrong, you can't go back to another tty to fix your issue.

**Comment by GrbavaCigla** [comment]
Did anyone come with OpenRC script, if yes please help me
