### ISSUE TITLE
Config not applying changes on color

### ISSUE THREAD

**Issue by mehtamanan0** [cylgom/ly#80]
I am unable to change colors by changing it in the config file

can anyone help?

thanks

![image](https://user-images.githubusercontent.com/16348397/46853610-39dd2300-ce1c-11e8-92c8-d50c68967159.png)

i'm trying to get a colorscheme as seen in the README

![image](https://user-images.githubusercontent.com/16348397/46853699-7a3ca100-ce1c-11e8-9bad-74d96a85355f.png)

**Comment by cylgom** [comment]
This option sets `truecolor` escape sequences, which are not supported by `tty`s. So actually it works, for example if you launch Ly in a terminal supporting `truecolor` in your desktop environment, but it's not really useful in practice since `tty`s don't support this. I need to add 256-color or 16-color support to enable `tty` customization.

**Comment by mehtamanan0** [comment]
@cylgom Thanks for clearing it out!
