### ISSUE TITLE
Multiple environment variables are not being set when using Ly

### ISSUE THREAD

**Issue by Wrapscallion** [cylgom/ly#9]
Using Arch with i3-gaps.

As far as I can tell, the login process for Ly seems to be like an [interactive, non-login shell](https://wiki.archlinux.org/index.php/Bash#Configuration_files), and so things like /etc/profile, /etc/profile.d, /etc/bash.bashrc, and my personal ~/.bash_profile are not being sourced or initialized in any way. This results in things like my LANG variable not being set as well as my PATH not being set correctly (for perl) because /etc/profile.d/locale.sh and /etc/profile.d/perlbin.sh are not being run.

I can get around these symptoms by sourcing /etc/profile directly in my .bashrc, but that is what I would personally consider to be a workaround? I don't know if pam has ways of setting this all correctly, I am not too familiar with it beyond a .pam_environment file.

**Comment by cylgom** [comment]
Hi,
Arch changed a few things recently which break this; Also Ly is definitely experimental software - I'm basically learning unix and coding this simultaneously. But I'll try to fix those asap, thank you for your interest!

**Comment by Wrapscallion** [comment]
Hey, you're doing much more than I can. :) It took me a couple of days to find everything out about login shells.

Currently my .bash_profile is the only thing that isn't being sourced or run in any way, so I suppose that .pam_environment can be used for the setting of environment variables? The only problem for me personally is that I don't know if it can even work as a perfect alternative to .bash_profile.

If some perfect alternatives exist, maybe just mention their necessity in documentation?

**Comment by oxodao** [comment]
He knows what I'm talking about, and since it's a bit related (According to him, ly does not set correct env vars in order to have gnome-keyring fully working [Actually I have no clue of what's happening, I just know that running i3-gaps through lightdm prevent the Nextcloud client from asking me my password, whereas it does in Ly]).

I know for example that in tmux you can source files through a command. Isn't that available in Bash? If so you can maybe do it within xinitrc script. Not the uglyiest hack I've ever done though

**Comment by cylgom** [comment]
It should work a lot better now, can try again with the latest commit ?

**Comment by Wrapscallion** [comment]
It seems to work! I no longer have to source /etc/profile. :) Thank you for your prompt response!

**Comment by cylgom** [comment]
You're welcome ;)
